---
# tasks file for 02-High-Availability
- name: Set sysctl
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    ignoreerrors: true

- name: Install packages RedHat
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name:
      - keepalived
      - haproxy
    state: present

- name: Copy keepalived.conf to master
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  register: keepalived_conf

- name: Enable keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Copy haproxy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  register: haproxy_conf

- name: Enable haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Restart keepalived
  when: keepalived_conf.changed
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart haproxy
  when: haproxy_conf.changed
  ansible.builtin.service:
    name: haproxy
    state: restarted
